/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as TrainingLessonIdRouteImport } from './routes/training/$lessonId'
import { Route as ToolsTaxRouteImport } from './routes/tools/tax'
import { Route as ToolsInvoiceRouteImport } from './routes/tools/invoice'
import { Route as ToolsContractsRouteImport } from './routes/tools/contracts'
import { Route as ToolsComplianceRouteImport } from './routes/tools/compliance'
import { Route as ResearchLoginRouteImport } from './routes/research/login'
import { Route as ResearchExportRouteImport } from './routes/research/export'
import { Route as ResearchDashboardRouteImport } from './routes/research/dashboard'
import { Route as AlitaStartRouteImport } from './routes/alita/start'
import { Route as AlitaSettingsSmeIdRouteImport } from './routes/alita/settings.$smeId'
import { Route as AlitaResultsAssessmentIdRouteImport } from './routes/alita/results.$assessmentId'
import { Route as AlitaGapsSmeIdRouteImport } from './routes/alita/gaps.$smeId'
import { Route as AlitaDashboardSmeIdRouteImport } from './routes/alita/dashboard.$smeId'
import { Route as AlitaAssessmentAssessmentIdRouteImport } from './routes/alita/assessment.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingLessonIdRoute = TrainingLessonIdRouteImport.update({
  id: '/training/$lessonId',
  path: '/training/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTaxRoute = ToolsTaxRouteImport.update({
  id: '/tools/tax',
  path: '/tools/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsInvoiceRoute = ToolsInvoiceRouteImport.update({
  id: '/tools/invoice',
  path: '/tools/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsContractsRoute = ToolsContractsRouteImport.update({
  id: '/tools/contracts',
  path: '/tools/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsComplianceRoute = ToolsComplianceRouteImport.update({
  id: '/tools/compliance',
  path: '/tools/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchLoginRoute = ResearchLoginRouteImport.update({
  id: '/research/login',
  path: '/research/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchExportRoute = ResearchExportRouteImport.update({
  id: '/research/export',
  path: '/research/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchDashboardRoute = ResearchDashboardRouteImport.update({
  id: '/research/dashboard',
  path: '/research/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlitaStartRoute = AlitaStartRouteImport.update({
  id: '/alita/start',
  path: '/alita/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AlitaSettingsSmeIdRoute = AlitaSettingsSmeIdRouteImport.update({
  id: '/alita/settings/$smeId',
  path: '/alita/settings/$smeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlitaResultsAssessmentIdRoute =
  AlitaResultsAssessmentIdRouteImport.update({
    id: '/alita/results/$assessmentId',
    path: '/alita/results/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlitaGapsSmeIdRoute = AlitaGapsSmeIdRouteImport.update({
  id: '/alita/gaps/$smeId',
  path: '/alita/gaps/$smeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlitaDashboardSmeIdRoute = AlitaDashboardSmeIdRouteImport.update({
  id: '/alita/dashboard/$smeId',
  path: '/alita/dashboard/$smeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlitaAssessmentAssessmentIdRoute =
  AlitaAssessmentAssessmentIdRouteImport.update({
    id: '/alita/assessment/$assessmentId',
    path: '/alita/assessment/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alita/start': typeof AlitaStartRoute
  '/research/dashboard': typeof ResearchDashboardRoute
  '/research/export': typeof ResearchExportRoute
  '/research/login': typeof ResearchLoginRoute
  '/tools/compliance': typeof ToolsComplianceRoute
  '/tools/contracts': typeof ToolsContractsRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/training/$lessonId': typeof TrainingLessonIdRoute
  '/training/': typeof TrainingIndexRoute
  '/alita/assessment/$assessmentId': typeof AlitaAssessmentAssessmentIdRoute
  '/alita/dashboard/$smeId': typeof AlitaDashboardSmeIdRoute
  '/alita/gaps/$smeId': typeof AlitaGapsSmeIdRoute
  '/alita/results/$assessmentId': typeof AlitaResultsAssessmentIdRoute
  '/alita/settings/$smeId': typeof AlitaSettingsSmeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alita/start': typeof AlitaStartRoute
  '/research/dashboard': typeof ResearchDashboardRoute
  '/research/export': typeof ResearchExportRoute
  '/research/login': typeof ResearchLoginRoute
  '/tools/compliance': typeof ToolsComplianceRoute
  '/tools/contracts': typeof ToolsContractsRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/training/$lessonId': typeof TrainingLessonIdRoute
  '/training': typeof TrainingIndexRoute
  '/alita/assessment/$assessmentId': typeof AlitaAssessmentAssessmentIdRoute
  '/alita/dashboard/$smeId': typeof AlitaDashboardSmeIdRoute
  '/alita/gaps/$smeId': typeof AlitaGapsSmeIdRoute
  '/alita/results/$assessmentId': typeof AlitaResultsAssessmentIdRoute
  '/alita/settings/$smeId': typeof AlitaSettingsSmeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alita/start': typeof AlitaStartRoute
  '/research/dashboard': typeof ResearchDashboardRoute
  '/research/export': typeof ResearchExportRoute
  '/research/login': typeof ResearchLoginRoute
  '/tools/compliance': typeof ToolsComplianceRoute
  '/tools/contracts': typeof ToolsContractsRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/training/$lessonId': typeof TrainingLessonIdRoute
  '/training/': typeof TrainingIndexRoute
  '/alita/assessment/$assessmentId': typeof AlitaAssessmentAssessmentIdRoute
  '/alita/dashboard/$smeId': typeof AlitaDashboardSmeIdRoute
  '/alita/gaps/$smeId': typeof AlitaGapsSmeIdRoute
  '/alita/results/$assessmentId': typeof AlitaResultsAssessmentIdRoute
  '/alita/settings/$smeId': typeof AlitaSettingsSmeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alita/start'
    | '/research/dashboard'
    | '/research/export'
    | '/research/login'
    | '/tools/compliance'
    | '/tools/contracts'
    | '/tools/invoice'
    | '/tools/tax'
    | '/training/$lessonId'
    | '/training/'
    | '/alita/assessment/$assessmentId'
    | '/alita/dashboard/$smeId'
    | '/alita/gaps/$smeId'
    | '/alita/results/$assessmentId'
    | '/alita/settings/$smeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alita/start'
    | '/research/dashboard'
    | '/research/export'
    | '/research/login'
    | '/tools/compliance'
    | '/tools/contracts'
    | '/tools/invoice'
    | '/tools/tax'
    | '/training/$lessonId'
    | '/training'
    | '/alita/assessment/$assessmentId'
    | '/alita/dashboard/$smeId'
    | '/alita/gaps/$smeId'
    | '/alita/results/$assessmentId'
    | '/alita/settings/$smeId'
  id:
    | '__root__'
    | '/'
    | '/alita/start'
    | '/research/dashboard'
    | '/research/export'
    | '/research/login'
    | '/tools/compliance'
    | '/tools/contracts'
    | '/tools/invoice'
    | '/tools/tax'
    | '/training/$lessonId'
    | '/training/'
    | '/alita/assessment/$assessmentId'
    | '/alita/dashboard/$smeId'
    | '/alita/gaps/$smeId'
    | '/alita/results/$assessmentId'
    | '/alita/settings/$smeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlitaStartRoute: typeof AlitaStartRoute
  ResearchDashboardRoute: typeof ResearchDashboardRoute
  ResearchExportRoute: typeof ResearchExportRoute
  ResearchLoginRoute: typeof ResearchLoginRoute
  ToolsComplianceRoute: typeof ToolsComplianceRoute
  ToolsContractsRoute: typeof ToolsContractsRoute
  ToolsInvoiceRoute: typeof ToolsInvoiceRoute
  ToolsTaxRoute: typeof ToolsTaxRoute
  TrainingLessonIdRoute: typeof TrainingLessonIdRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  AlitaAssessmentAssessmentIdRoute: typeof AlitaAssessmentAssessmentIdRoute
  AlitaDashboardSmeIdRoute: typeof AlitaDashboardSmeIdRoute
  AlitaGapsSmeIdRoute: typeof AlitaGapsSmeIdRoute
  AlitaResultsAssessmentIdRoute: typeof AlitaResultsAssessmentIdRoute
  AlitaSettingsSmeIdRoute: typeof AlitaSettingsSmeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$lessonId': {
      id: '/training/$lessonId'
      path: '/training/$lessonId'
      fullPath: '/training/$lessonId'
      preLoaderRoute: typeof TrainingLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tax': {
      id: '/tools/tax'
      path: '/tools/tax'
      fullPath: '/tools/tax'
      preLoaderRoute: typeof ToolsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/invoice': {
      id: '/tools/invoice'
      path: '/tools/invoice'
      fullPath: '/tools/invoice'
      preLoaderRoute: typeof ToolsInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/contracts': {
      id: '/tools/contracts'
      path: '/tools/contracts'
      fullPath: '/tools/contracts'
      preLoaderRoute: typeof ToolsContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compliance': {
      id: '/tools/compliance'
      path: '/tools/compliance'
      fullPath: '/tools/compliance'
      preLoaderRoute: typeof ToolsComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/login': {
      id: '/research/login'
      path: '/research/login'
      fullPath: '/research/login'
      preLoaderRoute: typeof ResearchLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/export': {
      id: '/research/export'
      path: '/research/export'
      fullPath: '/research/export'
      preLoaderRoute: typeof ResearchExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/dashboard': {
      id: '/research/dashboard'
      path: '/research/dashboard'
      fullPath: '/research/dashboard'
      preLoaderRoute: typeof ResearchDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/start': {
      id: '/alita/start'
      path: '/alita/start'
      fullPath: '/alita/start'
      preLoaderRoute: typeof AlitaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/settings/$smeId': {
      id: '/alita/settings/$smeId'
      path: '/alita/settings/$smeId'
      fullPath: '/alita/settings/$smeId'
      preLoaderRoute: typeof AlitaSettingsSmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/results/$assessmentId': {
      id: '/alita/results/$assessmentId'
      path: '/alita/results/$assessmentId'
      fullPath: '/alita/results/$assessmentId'
      preLoaderRoute: typeof AlitaResultsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/gaps/$smeId': {
      id: '/alita/gaps/$smeId'
      path: '/alita/gaps/$smeId'
      fullPath: '/alita/gaps/$smeId'
      preLoaderRoute: typeof AlitaGapsSmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/dashboard/$smeId': {
      id: '/alita/dashboard/$smeId'
      path: '/alita/dashboard/$smeId'
      fullPath: '/alita/dashboard/$smeId'
      preLoaderRoute: typeof AlitaDashboardSmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alita/assessment/$assessmentId': {
      id: '/alita/assessment/$assessmentId'
      path: '/alita/assessment/$assessmentId'
      fullPath: '/alita/assessment/$assessmentId'
      preLoaderRoute: typeof AlitaAssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlitaStartRoute: AlitaStartRoute,
  ResearchDashboardRoute: ResearchDashboardRoute,
  ResearchExportRoute: ResearchExportRoute,
  ResearchLoginRoute: ResearchLoginRoute,
  ToolsComplianceRoute: ToolsComplianceRoute,
  ToolsContractsRoute: ToolsContractsRoute,
  ToolsInvoiceRoute: ToolsInvoiceRoute,
  ToolsTaxRoute: ToolsTaxRoute,
  TrainingLessonIdRoute: TrainingLessonIdRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  AlitaAssessmentAssessmentIdRoute: AlitaAssessmentAssessmentIdRoute,
  AlitaDashboardSmeIdRoute: AlitaDashboardSmeIdRoute,
  AlitaGapsSmeIdRoute: AlitaGapsSmeIdRoute,
  AlitaResultsAssessmentIdRoute: AlitaResultsAssessmentIdRoute,
  AlitaSettingsSmeIdRoute: AlitaSettingsSmeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
